app/models.py
from werkzeug.security import generate_password_hash,check_password_hash
from . import db 
from flask_login import UserMixin
from . import login_manager,admin
from flask_sqlalchemy import SQLAlchemy


from flask_admin.contrib import sqla
from flask_admin.contrib.sqla import ModelView


class Comment(db.Model):
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(120))
    comment = db.Column(db.Text, nullable=False)

    def __str__(self):
        return self.comment


class Image(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Unicode(64))
    path = db.Column(db.Unicode(128))

    def __unicode__(self):
        return self.name

class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))
    email = db.Column(db.String(255),unique = True,index = True)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())

    pass_secure = db.Column(db.String(255))

    @property
    def password(self):
            raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)
    
    
    def __repr__(self):
        return f'User {self.username}'
    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))


class Role(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(255))
    users = db.relationship('User',backref = 'role',lazy="dynamic")
    
    def __repr__(self):
        return f'User {self.name}'

class PhotoProfile(db.Model):
    __tablename__ = 'profile_photos'

    id = db.Column(db.Integer,primary_key = True)
    pic_path = db.Column(db.String())
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))        


post_tags_table = db.Table('post_tags', db.Model.metadata,
                           db.Column('post_id', db.Integer, db.ForeignKey('post.id')),
        
                           )


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(120))
    text = db.Column(db.Text, nullable=False)
    date = db.Column(db.DateTime)

    user_id = db.Column(db.Integer(), db.ForeignKey(User.id))
    user = db.relationship(User, backref='posts')

    

    def __str__(self):
        return self.title
 

    def __init__(self, session):
        # Just call parent class with predefined model.
        super(PostAdmin, self).__init__(Post, session)



admin.add_view(ModelView(Post,db.session))
admin.add_view(ModelView(User,db.session))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import Required



class CommentForm(FlaskForm):
    
    username = StringField('username ',validators=[Required()])
    comment = TextAreaField('post comment', validators=[Required()])
    submit = SubmitField('post')

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')


   


    

app/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail
from flask_admin import Admin

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

admin = Admin()
bootstrap = Bootstrap()
db = SQLAlchemy()
from app.models import Comment

mail = Mail()
photos = UploadSet('photos',IMAGES)


def create_app(config_state):
    app = Flask(__name__)
    app.config.from_object(config_options[config_state])
    mail.init_app(app)
    # configure UploadSet
    
    configure_uploads(app,photos)
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    admin.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)

from . import views

app/main/views.py
from . import main
from flask import render_template,request,redirect,url_for,abort
from flask_login import login_required
from ..models import User,PhotoProfile,Post,Role
from .forms import UpdateProfile,CommentForm
from .. import db,photos

# Views

@main.route('/')
def index():
    '''
    View root page function that returns the index page and its data
    '''
    return render_template('index.html')



@main.route('/Comment', methods = ['GET','POST'])
def comment():
     form = CommentForm()
    
     if form.validate_on_submit():
        username.comment = form.username.data
        comment.comment =form.comment.data
        comment = comment(username,comment)
        db.session.add(comment)
        db.session.commit()

        return redirect(url_for('.comment'))
     return render_template('post_comment.html',CommentForm=form)

@main.route('/user/<uname>')
@login_required
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/pofile.html", user = user)


@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():

        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)


@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        user_photo = PhotoProfile(pic_path = path)
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))     

app/templates/base.html
{% extends 'bootstrap/base.html'%}

{%block styles%}
  {{super()}}

  <link href="https://fonts.googleapis.com/css?family=Black+Han+Sans" rel="stylesheet">

  <link rel="stylesheet" href="{{url_for('static',filename='index.css')}}">
{%endblock%}

{% block navbar %}
  {%include 'navbar.html'%}
{%endblock%}

app/templates/blog.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
<!-- Styles block -->

{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/movie.css')}}">
{% endblock %}

<!-- Content block -->
{% block content %}
<div class="container">

    <!-- Blog background -->
    <div class="row">
        
        {{ wtf.quick_form(BlogForm) }}


        </div>


    </div>
  

</div>
{% endblock %}

app/templates/index.html
{% extends 'base.html'%}


<!-- Styles block -->

{% block styles%}
{{ super() }}
<link href="https://fonts.googleapis.com/css?family=Gugi" rel="stylesheet" style="font-family: 'Gugi', cursive;">
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
    crossorigin="anonymous">
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}
<!-- Content block -->
{% block content %}

<div class="jumbotron" style="height:400px;background-image: url(static/photos/teamwork.jpg);background-repeat:no-repeat;background-color:rgba(20, 16, 16, 0.863);"
    )>

</div>
<div class="container" style="font-family: 'Gugi', cursive;">
    <h1>{{title}}</h1>
    {% if current_user.is_authenticated%}
    <h5 style="font-size:40px;text-align:center;">Hello {{current_user.username}}</h5>

    {% else %}
    <h2>CO-OPERATIVES BLOG </h2>
    {%endif%}


</div><br><br>
<div class="row">
    <div class="card">
        <div class="card-body">
            <img class="card-img-top" src="static/photos/union.jpg" alt="Card image cap">
            <h5 class="card-title" style="font-family: 'Gugi', cursive;">Welcome to the co-operatives world</h5>
            <a href="/Comment" class="btn btn-primary">Add comment</a>
        </div>
    </div><br><br>

    <div class="card">
        <div class="card-body">
            <img class="card-img-top" src="static/photos/spirit.jpg" alt="Card image cap">
            <h5 class="card-title" style="font-family: 'Gugi', cursive;">Teamwork</h5>
            <a href="/Comment" class="btn btn-primary">Add comment</a>
        </div>
    </div><br><br>
    <div class="card">
        <div class="card-body">
            <img class="card-img-top" src="static/photos/motivation.jpg" alt="Card image cap">
            <h5 class="card-title" style="font-family: 'Gugi', cursive;">Motivation</h5>
            <a href="/Comment" class="btn btn-primary">Add comment</a>
        </div>
    </div><br><br>
    <div class="card">
        <div class="card-body">
            <img class="card-img-top" src="static/photos/hardwork.jpg" alt="Card image cap">
            <h5 class="card-title" style="font-family: 'Gugi', cursive;">Hardwork </h5>
            <a href="/Comment" class="btn btn-primary">Add comment</a>
        </div>
    </div><br><br>
<div class="card">
    <div class="card-body">
        <img class="card-img-top" src="static/photos/cooperativefund.jpg" alt="Card image cap">
        <h5 class="card-title">Co-operative funding</h5>
        <a href="/Comment" class="btn btn-primary">Add comment</a>
    </div>
</div><br><br>
<div class="card">
    <div class="card-body">
        <img class="card-img-top" src="static/photos/communitywork.jpg" alt="Card image cap">
        <h5 class="card-title" style="font-family: 'Gugi', cursive;">Community Work</h5>
        <a href="/Comment" class="btn btn-primary">Add comment</a>
    </div>
</div>
</div>
<!-- </div> -->

{% endblock %}

app/templates/navbar.html
<div class="navbar navbar-defaullt" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"> Home </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/admin">Admin</a></li>
                <ul class="nav navbar-nav">
                    
                <ul class="nav navbar-nav navbar-left">
                        {% if current_user.is_authenticated %}
                       
                        <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                        <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
                        {% else %}
                        <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                        {%endif%}
                      </ul>
                      </ul>
                      
        </div>

    </div>
</div>

app/templates/post_comment.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
   
        

        <div class="col-md-4">

            {{ wtf.quick_form(CommentForm) }}
        </div>

    </div>

{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf %}
{% block styles%}
    {{ super() }}
    <link href="https://fonts.googleapis.com/css?family=Gugi" rel="stylesheet" style="font-family: 'Gugi', cursive;">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}
{% block content %}
 
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4"style="font-family: 'Gugi', cursive;">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
  </div>

  <!--Display profile photo-->
  <div class="col-md-4"style="font-family: 'Gugi', cursive;"></div>
  <div class= "card"style="font-family: 'Gugi', cursive;">
  
  
  <div class="col-md-4">
  {% if user.profile_pic_path %}
  <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
  {%else%}
  <p>No profile picture</p>
  {% endif %}

  <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

    <input type="file"  name="photo" class="form-control" required style="width:300px;font-family: 'Gugi', cursive;">
    <input type="submit">

  </form>
  {% if user == current_user %}
    <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
    {%else%}
    <p>No profile picture</p>

    {% endif %}
  <div style="margin: 24px 0;">
    <a href="#"><i class="fa fa-dribbble"></i></a> 
    <a href="#"><i class="fa fa-twitter"></i></a>  
    <a href="#"><i class="fa fa-linkedin"></i></a>  
    <a href="#"><i class="fa fa-facebook"></i></a> 
 </div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
  {{wtf.quick_form(form)}}
{% endblock %} 

app/templates/search.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
    <div class="container">

        <div class="col-md-8">

            <img src="{{post.image}}" alt="{{post.title}}" class="img-responsive">
        </div>

        <div class="col-md-4">

            {{ wtf.quick_form(review_form) }}
        </div>

    </div>

{% endblock %}